server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    password: xdq123
    username: root
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

  resources:
    static-locations: classpath:/static,file:/usr/xin-blog/blog-server

mybatis:
  configuration:
    map-underscore-to-camel-case: true


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

blog:
  file:
    rootPath: /usr/xin-blog/blog-server

  login:
    username: admin
    password: root